// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uthbwyximlfpkklrdqzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0aGJ3eXhpbWxmcGtrbHJkcXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3ODk5ODUsImV4cCI6MjA1NTM2NTk4NX0.1cM2CA_Whwwha2uAGToVZ1jtau-uYpqcGApyClckWFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);